# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QDoubleValidator

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(523, 378)
        Form.setMinimumSize(QtCore.QSize(523, 378))
        Form.setMaximumSize(QtCore.QSize(523, 378))
        self.formula1 = QtWidgets.QLabel(parent=Form)
        self.formula1.setGeometry(QtCore.QRect(10, 10, 351, 71))
        self.formula1.setText("")
        self.formula1.setPixmap(QtGui.QPixmap("./app/assets/Z1.png"))
        self.formula1.setScaledContents(True)
        self.formula1.setObjectName("formula1")
        self.formula2 = QtWidgets.QLabel(parent=Form)
        self.formula2.setGeometry(QtCore.QRect(10, 90, 181, 51))
        self.formula2.setText("")
        self.formula2.setPixmap(QtGui.QPixmap("./app/assets/Z2.png"))
        self.formula2.setScaledContents(True)
        self.formula2.setObjectName("formula2")
        self.boxA = QtWidgets.QLineEdit(parent=Form)
        self.boxA.setGeometry(QtCore.QRect(40, 200, 231, 21))
        self.boxA.setObjectName("boxA")
        self.boxA.setValidator(QDoubleValidator())
        self.labelA = QtWidgets.QLabel(parent=Form)
        self.labelA.setGeometry(QtCore.QRect(20, 200, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelA.setFont(font)
        self.labelA.setObjectName("labelA")
        self.labelComma = QtWidgets.QLabel(parent=Form)
        self.labelComma.setGeometry(QtCore.QRect(20, 280, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelComma.setFont(font)
        self.labelComma.setWordWrap(True)
        self.labelComma.setObjectName("labelComma")
        self.boxComma = QtWidgets.QSpinBox(parent=Form)
        self.boxComma.setGeometry(QtCore.QRect(160, 280, 61, 31))
        self.boxComma.setMinimum(2)
        self.boxComma.setObjectName("boxComma")
        self.buttonResult = QtWidgets.QPushButton(parent=Form)
        self.buttonResult.setGeometry(QtCore.QRect(380, 190, 113, 32))
        self.buttonResult.setObjectName("buttonResult")
        self.buttonClear = QtWidgets.QPushButton(parent=Form)
        self.buttonClear.setGeometry(QtCore.QRect(380, 230, 113, 32))
        self.buttonClear.setObjectName("buttonClear")
        self.buttonClose = QtWidgets.QPushButton(parent=Form)
        self.buttonClose.setGeometry(QtCore.QRect(380, 270, 113, 32))
        self.buttonClose.setObjectName("buttonClose")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Решение уравнений"))
        self.labelA.setText(_translate("Form", "α"))
        self.labelComma.setText(_translate("Form", "Количество знаков после запятой"))
        self.buttonResult.setText(_translate("Form", "Результат"))
        self.buttonClear.setText(_translate("Form", "Очистить"))
        self.buttonClose.setText(_translate("Form", "Закрыть"))
